#!/bin/sh

# returns the value of a property within a property file
# call `prop file propName'
prop() {
    if [ ! -f "$1" ]; then
        return
    fi
    grep "^\\s*${2}=" ${1} | cut -d'=' -f2
}

# call `propJavaVersion currentDir
propJavaVersion() {
  local version=$(prop $1/jeka/local.properties jeka.java.version)
  version=$(echo $version | sed 's/ //g')
  if [ -z $version ]
  then
    if [ -d "${1}/../jeka" ]
    then
      echo $(propJavaVersion "${1}/..")
    else
      echo ""
    fi
    return
  fi
  echo $version
}

# call `propJdkVersion currentDir javaVersion`
propJdkHome() {
  local envValue=$(printenv "JEKA_JDK_${2}")
  if [ ! -z $envValue ]; then
    echo $envValue
    return
  fi
  envValue=$(printenv "jeka.jdk.${2}")
  if [ ! -z $envValue ]; then
    echo $envValue
    return
  fi
  local propName="jeka.jdk.${2}"
  local path=$(prop $1/jeka/local.properties $propName)
  path=$(echo $version | sed 's/ //g')
  if [ -z $path ]
  then
    if [ -d "${1}/../jeka" ]
    then
      path=$(propJdkHome "${1}/.." ${2})
    else
      local jekaUserHome=$JEKA_USER_HOME
      if [ -z $jekaUserHome ]; then
        jekaUserHome=~/.jeka
      fi
      propFile=$jekaUserHome/global.properties
      path=$(prop $propFile $propName)
    fi
  fi
  echo $path
}

if [ -z "$Jeka_OPTS" ] ; then
  export "JEKA_OPTS= "
fi

if [ -n "$JEKA_JDK" ] ; then
  export JAVA_HOME=$JEKA_JDK
  else
    workingDir=$(pwd)
    javaVersion=$(propJavaVersion $workingDir)
    if [ ! -z $javaVersion ]; then
      jdkPath=$(propJdkHome $workingDir $javaVersion)
      if [ ! -z $jdkPath ]; then
        export JAVA_HOME=$jdkPath
      fi
    fi
fi

# OS specific support.  $var _must_ be set to either true or false.
cygwin=false;
darwin=false;
mingw=false
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  MINGW*) mingw=true;;
  Darwin*) darwin=true
           #
           # Look for the Apple JDKs first to preserve the existing behaviour, and then look
           # for the new JDKs provided by Oracle.
           #
           if [ -z "$JAVA_HOME" ] && [ -L /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK ] ; then
             #
             # Apple JDKs
             #
             export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home
           fi

           if [ -z "$JAVA_HOME" ] && [ -L /System/Library/Java/JavaVirtualMachines/CurrentJDK ] ; then
             #
             # Apple JDKs
             #
             export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home
           fi

           if [ -z "$JAVA_HOME" ] && [ -L "/Library/Java/JavaVirtualMachines/CurrentJDK" ] ; then
             #
             # Oracle JDKs
             #
             export JAVA_HOME=/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home
           fi

           if [ -z "$JAVA_HOME" ] && [ -L "/usr/libexec/java_home" ]; then
             #
             # Apple JDKs
             #
             export JAVA_HOME=`/usr/libexec/java_home`
           fi
           ;;
esac

if [ -z "$JAVA_HOME" ] ; then
  if [ -r /etc/gentoo-release ] ; then
    JAVA_HOME=`java-config --jre-home`
  fi
fi

if [ -z "$JEKA_HOME" ] ; then
  ## resolve links - $0 may be a link to jeka's home
  PRG="$0"

  # need this for relative symlinks
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG="`dirname "$PRG"`/$link"
    fi
  done

  saveddir=`pwd`

  JEKA_HOME=`dirname "$PRG"`

  # make it fully qualified
  JEKA_HOME=`cd "$JEKA_HOME" && pwd`

  cd "$saveddir"
fi

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
  [ -n "$JEKA_HOME" ] &&
    JEKA_HOME=`cygpath --unix "$JEKA_HOME"`
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
  [ -n "$CLASSPATH" ] &&
    CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

# For Migwn, ensure paths are in UNIX format before anything is touched
if $mingw ; then
  [ -n "$JEKA_HOME" ] &&
    JEKA_HOME="`(cd "$JEKA_HOME"; pwd)`"
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME="`(cd "$JAVA_HOME"; pwd)`"
fi

if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
      # IBM's JDK on AIX uses strange locations for the executables
      JAVACMD="$JAVA_HOME/jre/sh/java"
    else
      JAVACMD="$JAVA_HOME/bin/java"
    fi
  else
    JAVACMD="`which java`"
  fi
fi

if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly (valued to $JAVA_HOME )." >&2
  echo "  We cannot execute $JAVACMD" >&2
  echo "  You can specify which JDK to use by setting JEKA_JDK environment variable." >&2
  exit 1
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  [ -n "$JEKA_HOME" ] &&
    JEKA_HOME=`cygpath --path --windows "$JEKA_HOME"`
  [ -n "$JAVA_HOME" ] &&
    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
  [ -n "$CLASSPATH" ] &&
    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
fi

# Provide a "standardized" way to retrieve the CLI args that will
# work with both Windows and non-Windows executions.
JEKA_CMD_LINE_ARGS="$@"
export JEKA_CMD_LINE_ARGS

if [ -d "./jeka/boot" ]; then
   LOCAL_BUILD_DIR="./jeka/boot/*:"
else
   LOCAL_BUILD_DIR=""
fi

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
exec "$JAVACMD" $JEKA_OPTS -cp "$LOCAL_BUILD_DIR$SCRIPTPATH/jeka/wrapper/*" dev.jeka.core.wrapper.Booter $SCRIPTPATH "$@"