GET https://oss.sonatype.org/service/local/staging/profile_repositories
Accept: application/xml
Authorization: basic {{basic}}


###

POST https://oss.sonatype.org/service/local/staging/bulk/close
Accept: application/json
Content-Type: application/json
Authorization: basic {{basic}}

{"data":{"stagedRepositoryIds":["devjeka-1145"]}}


###

GET https://oss.sonatype.org/service/local/staging/repository/devjeka-1145
Accept: application/xml
Authorization: basic {{basic}}

###
POST https://oss.sonatype.org/service/local/staging/bulk/promote
accept: application/json
content-type: application/json
authorization: basic {{basic}}

{"data":{"autoDropAfterRelease":true,"stagedRepositoryIds":["devjeka-1145"]}}


